### ISSUE TITLE
生成的二维码没有铺满整个canvas

### ISSUE THREAD

**Issue by sunfloweryll** [theomessin/vue-qriously#11]
![image](https://user-images.githubusercontent.com/15272750/39851111-bec2e888-5447-11e8-9ab6-a6b80bdd8b49.png)

**Comment by sunfloweryll** [comment]
我设置的宽和高是86，虽然canvas好宽个高也是86，但是生成的二维码没有铺满整个canvas，不知道什么原因，也没有找到类似的问题，麻烦回复一下，谢谢

**Comment by theomessin** [comment]
English only
