### ISSUE TITLE
背景色不显示，backgroundAlpha属性默认为0

### ISSUE THREAD

**Issue by sunxingchen1995** [theomessin/vue-qriously#13]
希望作者能把属性写全一些，设置背景色无效果，以为是bug呢，看了组件才知道默认透明度是0。。。
backgroundAlpha设置为1就好了

**Comment by theomessin** [comment]
I don't speak what I can only assume is Chinese...

**Comment by sunxingchen1995** [comment]
ahaha,I'm so sorry.
I didn't look at it carefully and thought you were Chinese, tooooooo.....
