### ISSUE TITLE
When backgroundAlpha is 0.0, the image saved on Chrome can't be scanned in some programs like wechat. 

### ISSUE THREAD

**Issue by luffyfly** [theomessin/vue-qriously#22]
The default backgroundAlpha of vue-qriously is 0.0, but qriously default  backgroundAlpha is 1.0.
I think it's better to set backgroundAlpha  to 1.0 as default.

**Comment by theomessin** [comment]
Agree, submit a PR and I'll get it merged. Too busy to deal with changing this myself. Additionally, I am considering archiving this package as qrious seams to be a dead project (and this is just a vue wrapper)

**Comment by luffyfly** [comment]
I have created a pull request, please check.

**Comment by theomessin** [comment]
Merged. However, a release is blocked due to #24

**Comment by theomessin** [comment]
I'm deprecating this package.
