### ISSUE TITLE
Build script is broken

### ISSUE THREAD

**Issue by theomessin** [theomessin/vue-qriously#24]
Trying to run `npm run build` yields:

```
🚨   (vue plugin) Unknown transform 'collections'
```
This is probably due to updates in vue and the rest of the build tooling.

This package is nearing the end of its lifetime. The original package qrious seems to be dead as well https://github.com/neocotic/qrious/issues/121.

**Comment by theomessin** [comment]
I will probably be deprecating the package and archiving the repo in a couple of weeks.

**Comment by luffyfly** [comment]
I have upgraded rollup and  make a pr. Please check.

**Comment by theomessin** [comment]
I'm deprecating this package.
