### ISSUE TITLE
Plugin bricks UglifyJs

### ISSUE THREAD

**Issue by jxZhangLi** [theomessin/vue-qriously#4]
![image](https://user-images.githubusercontent.com/16809535/27466240-b8c67e9c-580b-11e7-9f30-60360765ae30.png)

**Comment by jxZhangLi** [comment]
@theomessin

**Comment by theomessin** [comment]
Use English please.

**Comment by theomessin** [comment]
Try now with version `1.0.1`

**Comment by jxZhangLi** [comment]
What I'm using is vue-qriously "^1.0.0" ，vue-cli  The packaging file has a problem

**Comment by theomessin** [comment]
I published a new version with a fix though. That's why I specified `1.0.1`.

**Comment by jxZhangLi** [comment]
I'm installing an error now  [1.01]  ![image](https://user-images.githubusercontent.com/16809535/27468204-18aa0446-581b-11e7-93d9-7da5f04a38ff.png)

**Comment by theomessin** [comment]
I don't think this has anything to do with `vue-qriously`.

**Comment by theomessin** [comment]
I'm gonna rewrite the way this plugin is bundled when I have the time. Till then I suggest you don't use it for production.

**Comment by theomessin** [comment]
Fixed with version `1.1.0`
