### ISSUE TITLE
error import the module, does it lack a index.js file in the main folder

### ISSUE THREAD

**Issue by Gtanghaibo** [theomessin/vue-qriously#5]
is there necessary a index.js file in the main folder
import module
![image](https://user-images.githubusercontent.com/15169083/27761212-2b0fec5c-5e8a-11e7-9b64-2ec18de47b29.png)
error message
![image](https://user-images.githubusercontent.com/15169083/27761233-6d4d9092-5e8a-11e7-87cf-01f837aa07cd.png)
lack the index.js file in the main folder
![image](https://user-images.githubusercontent.com/15169083/27761241-86294890-5e8a-11e7-9d57-46001c5364d4.png)

**Comment by theomessin** [comment]
That underscore is not supposed to be there I believe. Also, I'd suggest you don't use this package for production. Try again withouth the underscore and with version `1.0.0`

**Comment by theomessin** [comment]
Fixed with version `1.1.0`
