### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by hhhuaang** [theomessin/vue-qriously#6]
after me  install vue-qriously by npm 
i use it like this:
```
import VueQriously from 'vue-qriously'
Vue.use(VueQriously)

```
but its error 
![image](https://user-images.githubusercontent.com/10963105/28197346-cb6b2524-6888-11e7-9026-a26a3379f5d6.png)

the version is  vue-qriously@1.1.0

**Comment by theomessin** [comment]
Let me know if version `1.1.1` does the trick
